version: '3.8'
services:
  db-server:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: "exit 0" #further research on this
  adminer:
    image: adminer
    depends_on:
      - db-server
    restart: always
    ports:
      - 8080:8080
  keycloak-server:
    image: auth-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env.kc
    ports:
      - "8082:8080"
    depends_on:
      db-server:
        condition: service_healthy
    entrypoint: [ "/startup-scripts/kc-entrypoint.sh", "start-dev" ]
volumes:
  postgres_data:
